
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - anywhere.eks.amazonaws.com
  resources:
  - awsiamconfigs
  - bundles
  - clusters
  - dockerdatacenterconfigs
  - snowmachineconfigs
  - vspheredatacenterconfigs
  - vspheremachineconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - anywhere.eks.amazonaws.com
  resources:
  - awsiamconfigs/finalizers
  - bundles/finalizers
  - clusters/finalizers
  - dockerdatacenterconfigs/finalizers
  - vspheredatacenterconfigs/finalizers
  - vspheremachineconfigs/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - anywhere.eks.amazonaws.com
  resources:
  - awsiamconfigs/status
  - bundles/status
  - clusters/status
  - dockerdatacenterconfigs/status
  - snowmachineconfigs/status
  - vspheredatacenterconfigs/status
  - vspheremachineconfigs/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - anywhere.eks.amazonaws.com
  resources:
  - oidcconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - distro.eks.amazonaws.com
  resources:
  - releases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - test
  resources:
  - test
  verbs:
  - create
  - delete
  - get
  - kill
  - list
  - patch
  - update
  - watch
